name: Build EXE (Windows)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. リポジトリ取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Pythonセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      # 3. 依存ライブラリインストール
      - name: Install dependencies
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install selenium
          pip install chromedriver_binary
          if exist requirements.txt pip install -r requirements.txt

      # 4. exeビルド（chromedriver_binary 対応）
      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          
          REM PyInstaller に hidden-import と chromedriver のバイナリを追加
          pyinstaller --onefile equibase\03\equibase03_single.py ^
              --hidden-import=selenium ^
              --hidden-import=chromedriver_binary ^
              --add-data "%LOCALAPPDATA%\Python\Python311\Lib\site-packages\chromedriver_binary\chromedriver.exe;chromedriver_binary"

          REM exeの存在確認とリネーム
          if exist dist\equibase03_single.exe rename dist\equibase03_single.exe equibase03_single_final.exe

      # 5. Artifactsアップロード
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: equibase03_exe
          path: dist\equibase03_single_final.exe
